config/routes.rb
Rails.application.routes.draw do
  resources :values
  resources :visions
  root to: "welcome#home"
  get 'welcome/home'
  
  
  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :vision
  has_many :value
  
end

app/models/value.rb
class Value < ActiveRecord::Base
    belongs_to :user
end

app/models/vision.rb
class Vision < ActiveRecord::Base
    belongs_to :user
    
    STYLES= %w[olivia earn solange jesse]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :firstname
    devise_parameter_sanitizer.for(:sign_up) << :lastname
    devise_parameter_sanitizer.for(:sign_up) << :classyear
    devise_parameter_sanitizer.for(:sign_up) << :school
  end

end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_value, only: [:show, :edit, :update, :destroy]

  # GET /values
  # GET /values.json
  def index
    @values = Value.all
  end

  # GET /values/1
  # GET /values/1.json
  def show
  end

  # GET /values/new
  def new
    @value = current_user.value.build
  end

  # GET /values/1/edit
  def edit
  end

  # POST /values
  # POST /values.json
  def create
    @value = current_user.value.build(value_params)

    respond_to do |format|
      if @value.save
        format.html { redirect_to @value, notice: 'Value was successfully created.' }
        format.json { render :show, status: :created, location: @value }
      else
        format.html { render :new }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values/1
  # PATCH/PUT /values/1.json
  def update
    respond_to do |format|
      if @value.update(value_params)
        format.html { redirect_to @value, notice: 'Value was successfully updated.' }
        format.json { render :show, status: :ok, location: @value }
      else
        format.html { render :edit }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values/1
  # DELETE /values/1.json
  def destroy
    @value.destroy
    respond_to do |format|
      format.html { redirect_to values_url, notice: 'Value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value
      @value = Value.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def value_params
      params.require(:value).permit(:whoserve, :howserve, :legacy)
    end
end

app/controllers/visions_controller.rb
class VisionsController < ApplicationController
  before_action :set_vision, only: [:show, :edit, :update, :destroy]

  # GET /visions
  # GET /visions.json
  def index
    @visions = Vision.all
  end

  # GET /visions/1
  # GET /visions/1.json
  def show
  end

  # GET /visions/new
  def new
    @vision = current_user.vision.build
  end

  # GET /visions/1/edit
  def edit
  end

  # POST /visions
  # POST /visions.json
  def create
    @vision = current_user.vision.build(vision_params)

    respond_to do |format|
      if @vision.save
        format.html { redirect_to new_value_path, notice: 'Vision was successfully created.' }
        format.json { render :show, status: :created, location: @vision }
      else
        format.html { render :new }
        format.json { render json: @vision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visions/1
  # PATCH/PUT /visions/1.json
  def update
    respond_to do |format|
      if @vision.update(vision_params)
        format.html { redirect_to @vision, notice: 'Vision was successfully updated.' }
        format.json { render :show, status: :ok, location: @vision }
      else
        format.html { render :edit }
        format.json { render json: @vision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visions/1
  # DELETE /visions/1.json
  def destroy
    @vision.destroy
    respond_to do |format|
      format.html { redirect_to visions_url, notice: 'Vision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vision
      @vision = Vision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vision_params
      params.require(:vision).permit(:industry, :ten, :dreamjob, :style)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/helpers/visions_helper.rb
module VisionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloc </title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>

 

    <!-- Materialize Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <!-- Materialize Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <!-- FONTS --> 
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
     <!-- STYLESHEETS -->
     <link rel="stylesheet" href="../../assets/css/style.css">

     <!-- VENDOR SCRIPTS -->
     <!-- jquery -->
     <script type="text/javascript" src="http://code.jquery.com/jquery-2.2.2.min.js"></script>
     <!-- handlebars -->
     <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script> -->

     <!-- APPLICATION SCRIPTS -->
     <script src="../../assets//javascripts/scripts/data.js"></script>
     <script src="../../assets/javascripts/scripts/app.js"></script>
     <!-- CSS  -->
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

     <link href="../../assets/stylesheets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
     <link href="../../assets/stylesheets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>

<body>
    
    <nav>
    <div class="nav-wrapper white">
      <a href="#!" class="brand-logo black-text">BLOC </a>
      <a href="#" data-activates="mobile-demo" class="button-collapse black-text"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down ">
        <li><a class="black-text" href="sass.html">Profile</a></li>
        <li><a class="black-text" href="badges.html">Notifications</a></li>
        
      </ul>
      
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a href="mobile.html">Mobile</a></li>
      </ul>
    </div>
  </nav>
    
    
    
    
    
    

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>


<%= yield %>

  
<footer class="page-footer white">  
 </footer>
</body>

</html>

<style>

body {
	background: url("http://www.ourbloc.co/uploads/2/4/0/1/24014742/ilike_orig.jpg") no-repeat center center fixed;
	margin: 0 auto;
	background-size: cover;
	width: 100%;
	}
	
.page-footer{
	
    height: 10em;
    border-style: solid;
    border-width: .5em 0em 0em 0em ;
    border-color: teal;
   
  } 
</style>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/values/_form.html.erb
<%= form_for(@value) do |f| %>
  <% if @value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@value.errors.count, "error") %> prohibited this value from being saved:</h2>

      <ul>
      <% @value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :whoserve %><br>
    <%= f.text_field :whoserve %>
  </div>
  <div class="field">
    <%= f.label :howserve %><br>
    <%= f.text_field :howserve %>
  </div>
  <div class="field">
    <%= f.label :legacy %><br>
    <%= f.text_area :legacy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/values/edit.html.erb
<h1>Editing Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @value %> |
<%= link_to 'Back', values_path %>

app/views/values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Values</h1>

<table>
  <thead>
    <tr>
      <th>Whoserve</th>
      <th>Howserve</th>
      <th>Legacy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @values.each do |value| %>
      <tr>
        <td><%= value.whoserve %></td>
        <td><%= value.howserve %></td>
        <td><%= value.legacy %></td>
        <td><%= link_to 'Show', value %></td>
        <td><%= link_to 'Edit', edit_value_path(value) %></td>
        <td><%= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Value', new_value_path %>

app/views/values/new.html.erb
<h1 id="vision-header"> 2. WHAT ARE YOUR VALUES? </h1>

<div class="profile-back">
  <%= form_for(@value) do |f| %>
    <% if @value.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@value.errors.count, "error") %> prohibited this value from being saved:</h2>
  
        <ul>
        <% @value.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
      <%= f.label "How do you serve your community"  , :class => "fieldtext"  %> <br>
      <%= f.text_area :howserve , :class => "fieldtext"  %>
  </div> 
    
  <div class="field">
    <%= f.label "Who do you serve/ pay it forward to?"  , :class => "fieldtext"  %><br>
    <%= f.text_area :whoserve , :class => "fieldtext"  %>
  </div>
  
  <div class= "field">
    <%= f.label "What legacy are you building"  , :class => "fieldtext"  %> <br>
    <%= f.text_area :legacy, :class => "fieldtext"  %>
  </div>

  <div class="waves-effect waves-light btn" id="signupbtn">
     <%= f.label "Save Values"  %>
    <%= f.submit  %>
  </div>
<% end %>

<%= link_to 'Back', values_path %>
</div>

<style> 

#vision-header{
    font-size: 6em;
    color: white;
    top: 4em;
   
}

.field {
    width: 100%;
    left: 0%;
}
.profile-back{
    background-color: white;
    opacity: 1;
    position: absolute;
    height: 100%;
    padding: 1em 1em 3em 1em;
    width: 100%;
    left: 0em;
}

.fieldtext {
  left: 10%;
  font-size: 4em;
  color: black;
  height: 20%;
  width: 90%;
  line-height: 1.5;
}

input.fieldtext {
  font-size: 4em;
  line-height: 1.5;
  color: black;
  height: 10%;
  color: teal
  width: 60%;
}



#signupbtn{
  color: white;
  position: absolute;
  font-size: 4em;
  margin-top: 5%;
  left: 20%;
  height: 5%;
  width: 70%;
}


</style>

app/views/values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Whoserve:</strong>
  <%= @value.whoserve %>
</p>

<p>
  <strong>Howserve:</strong>
  <%= @value.howserve %>
</p>

<p>
  <strong>Legacy:</strong>
  <%= @value.legacy %>
</p>

<%= link_to 'Edit', edit_value_path(@value) %> |
<%= link_to 'Back', values_path %>

app/views/visions/_form.html.erb
<%= form_for(@vision) do |f| %>
  <% if @vision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vision.errors.count, "error") %> prohibited this vision from being saved:</h2>

      <ul>
      <% @vision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :ten %><br>
    <%= f.text_field :ten %>
  </div>
  <div class="field">
    <%= f.label :dreamjob %><br>
    <%= f.text_field :dreamjob %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visions/edit.html.erb
<h1>Editing Vision</h1>

<%= render 'form' %>

<%= link_to 'Show', @vision %> |
<%= link_to 'Back', visions_path %>

app/views/visions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visions</h1>

<table>
  <thead>
    <tr>
      <th>Industry</th>
      <th>Ten</th>
      <th>Dreamjob</th>
      <th>Style</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visions.each do |vision| %>
      <tr>
        <td><%= vision.industry %></td>
        <td><%= vision.ten %></td>
        <td><%= vision.dreamjob %></td>
        <td><%= vision.style %></td>
        <td><%= link_to 'Show', vision %></td>
        <td><%= link_to 'Edit', edit_vision_path(vision) %></td>
        <td><%= link_to 'Destroy', vision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vision', new_vision_path %>

app/views/visions/new.html.erb
<h1 id="vision-header"> 1. MAP YOUR VISION </h1> 

<div class="profile-back">
<%= form_for(@vision) do |f| %>
  <% if @vision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vision.errors.count, "error") %> prohibited this vision from being saved:</h2>

      <ul>
      <% @vision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  

  <div class="field">
    <%= f.label "I Will be the Steph Curry of", :class => "fieldtext" %>
    <%= f.text_field :industry , :placeholder => "which industry?" , :class => "fieldtext" %> 
  </div>
  <br style="height: 15%"> 
  
  
  
  <div class="field">
    <%= f.label "In ten years I will be dominiating my field in" , :class => "fieldtext"%>
    <%= f.text_field :ten , :placeholder => "what title/position", :class => "fieldtext" %>
  </div>
  <br> 
  <br> 
 
  <div class="field">
    <%= f.label "My first dream job is " , :class => "fieldtext"%>
    <%= f.text_field :dreamjob , :placeholder => "think BIG...", :class => "fieldtext" %>

  </div>
    
    
  
  
  <div class="waves-effect waves-light btn" id="signupbtn">
    <%= f.submit  %>
  </div>
<% end %>


<%= link_to 'Back', visions_path %>

</div>

<style> 

#vision-header{
    font-size: 6em;
    color: white;
    top: 4em;
    padding: 5%;
}

.profile-back{
    background-color: white;
    opacity: 1;
    position: absolute;
    height: 100%;
    padding: 5em 4em;
    top: 20%;
}

.fieldtext {
  font-size: 4em;
  padding: 10% 5%;
  height: 20%;
  line-height: 1.1;
}

input.fieldtext {
  font-size: 4em;
  color: teal;
  height: 10%;
}

.field {
  margin: 10%;
}

#signupbtn{
  color: white;
  position: relative;
  font-size: 4em;
  margin-top: 5%;
  left: 20%;
  height: 20%;
  width: 70%;
}



</style>

app/views/visions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="profile-back">
<p>
  <strong>User:</strong>
  <%= @vision.user.firstname %>
</p>

<p>
  <strong> I will be the Oprah of </strong> 
  <%= @vision.industry %>
</p>

<p>
  <strong> In ten years I will be a </strong>
  <%= @vision.ten %>
</p>

<p>
  <strong>My dream first job </strong>
  <%= @vision.dreamjob %>
</p>


<%= link_to 'Edit', edit_vision_path(@vision) %> |
<%= link_to 'Back', visions_path %>

</div>

<style>
.profile-back{
    font-family: Montserrat;
    background-color: white;
    opacity: 1;
    position: absolute;
    height: 60%;
    padding: 5em 4em;
    width: 100%;
}

p{
  font-family: Montserrat;
  font-size: 4em;
}

</style>

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BLOC</title>

    <!-- Materialize Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <!-- Materialize Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <!-- FONTS --> 
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
     <!-- STYLESHEETS -->
    <link rel="stylesheet" href="../../assets/css/style.css">

     <!-- VENDOR SCRIPTS -->
     <!-- jquery -->
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.2.2.min.js"></script>
     <!-- handlebars -->
     <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script> -->

     <!-- APPLICATION SCRIPTS -->
     <script src="../../assets//javascripts/scripts/data.js"></script>
     <script src="../../assets/javascripts/scripts/app.js"></script>
     <!-- CSS  -->
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

     <link href="../../assets/stylesheets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
     <link href="../../assets/stylesheets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  </head>
  
  
    <h2 id="core-head"> YOU CAN HAVE A THE CAREER OF YOUR DREAMS & SERVE YOUR COMMUNITY </h2>


  
       <button id="firstbutton"class=" white-text btn waves-effect waves-light "> <%= link_to "CREATE YOUR ROADMAP NOW", new_vision_path, class: "white-text" %></button>
      
      <div style="height: 20em"> </div>
  

    <!-- <div id="department-list" class="department-container">
      <script id="department-list-template" type="text/x-handlebars-template">
        <div class="container">

          {{#each department}}
          <div class="row">
            <div class="col l6 center">
              <div class="card" id="{{name}}-department">
                <div class="card-image waves-effect waves-block waves-light">
                  <img class="activator" src="images/department/{{name}}.jpeg">
                </div>
                <div class="card-content">
                  <span class="card-title activator grey-text text-darken-4">{{name}}<i class="material-icons right">more_vert</i></span> -->
                  <!-- <p><a href="">{{name}}</a></p> -->
                <!-- </div>
                <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4">{{name}}<i class="material-icons right">close</i></span>
                  <p>{{description}}</p>
                </div>
              </div>
            </div>
          </div>
          {{/each}}

        </div>
      </script>
    </div> -->




    

     <!--  Scripts-->
     <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
     <script src="../../assets/javascripts/scripts/materialize.js"></script>
     <script src="../../assets/javascripts/scripts/materialize.min.js"></script>
     <script src="../../assets/javascripts/scripts/init.js"></script>
     <script scr="../../assets/javascripts/scripts/app.js"></script>
     <script src="../../assets/javascripts/scripts/data.js"></script>
     </body>
</html>


<style>
  
  
  ul  {
    color:black;
    line-height: 1.2;
  }
  
  #firstbutton{
    left: 10%;
   
    width: 80%;
    color: white;
    height: 4em;
    font-size: 6em ;
    line-height: 1.2;
    border-radius: 3%;
  }
  
  
  
  
  
</style>